[2025-05-05 11:41:33,721] 97 werkzeug - WARNING -  * Debugger is active!
[2025-05-05 11:41:33,724] 97 werkzeug - INFO -  * Debugger PIN: 143-783-530
[2025-05-05 11:41:40,504] 97 werkzeug - INFO - 127.0.0.1 - - [05/May/2025 11:41:40] "GET / HTTP/1.1" 200 -
[2025-05-05 11:41:40,578] 97 werkzeug - INFO - 127.0.0.1 - - [05/May/2025 11:41:40] "GET /static/style.css HTTP/1.1" 200 -
[2025-05-05 11:41:40,603] 97 werkzeug - INFO - 127.0.0.1 - - [05/May/2025 11:41:40] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2025-05-05 11:42:25,888] 62 root - INFO - Dataframe Gathered
[2025-05-05 11:42:25,888] 48 root - INFO - Input DataFrame created:
[2025-05-05 11:42:25,903] 49 root - INFO - 
  Location  Temperature  Humidity  Wind_Speed  Precipitation Cloud_Cover
0   austin         26.0       6.0        50.0           34.0      cloudy
[2025-05-05 11:42:25,905] 53 root - INFO - Exception Occured in load_object function utils
[2025-05-05 11:42:25,905] 64 root - ERROR - Error during prediction:
[2025-05-05 11:42:25,905] 67 root - ERROR - Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\app.py] line number [53] error message [Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\pipelines\Prediction_pipeline.py] line number [18] error message [Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\utils\utils.py] line number [50] error message [[Errno 2] No such file or directory: 'Artifacts\\preprocessor.pkl']]]
[2025-05-05 11:42:25,907] 97 werkzeug - INFO - 127.0.0.1 - - [05/May/2025 11:42:25] "POST /predict HTTP/1.1" 200 -
[2025-05-05 11:42:25,928] 97 werkzeug - INFO - 127.0.0.1 - - [05/May/2025 11:42:25] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-05-05 11:43:05,872] 62 root - INFO - Dataframe Gathered
[2025-05-05 11:43:05,872] 48 root - INFO - Input DataFrame created:
[2025-05-05 11:43:05,876] 49 root - INFO - 
     Location  Temperature  Humidity  Wind_Speed  Precipitation Cloud_Cover
0  washington         24.0      23.0        60.0           45.0      cloudy
[2025-05-05 11:43:05,876] 53 root - INFO - Exception Occured in load_object function utils
[2025-05-05 11:43:05,876] 64 root - ERROR - Error during prediction:
[2025-05-05 11:43:05,876] 67 root - ERROR - Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\app.py] line number [53] error message [Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\pipelines\Prediction_pipeline.py] line number [18] error message [Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\utils\utils.py] line number [50] error message [[Errno 2] No such file or directory: 'Artifacts\\preprocessor.pkl']]]
[2025-05-05 11:43:05,878] 97 werkzeug - INFO - 127.0.0.1 - - [05/May/2025 11:43:05] "POST /predict HTTP/1.1" 200 -
[2025-05-05 11:43:05,908] 97 werkzeug - INFO - 127.0.0.1 - - [05/May/2025 11:43:05] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-05-05 11:45:06,782] 97 werkzeug - INFO -  * Detected change in 'C:\\Users\\Praveen\\OneDrive\\Desktop\\weather_prediction\\app.py', reloading
